require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TestQuestionsController do

  def mock_test_question(stubs={})
    @mock_test_question ||= mock_model(TestQuestion, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all test_questions as @test_questions" do
      TestQuestion.stub(:all) { [mock_test_question] }
      get :index
      assigns(:test_questions).should eq([mock_test_question])
    end
  end

  describe "GET show" do
    it "assigns the requested test_question as @test_question" do
      TestQuestion.stub(:find).with("37") { mock_test_question }
      get :show, :id => "37"
      assigns(:test_question).should be(mock_test_question)
    end
  end

  describe "GET new" do
    it "assigns a new test_question as @test_question" do
      TestQuestion.stub(:new) { mock_test_question }
      get :new
      assigns(:test_question).should be(mock_test_question)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_question as @test_question" do
      TestQuestion.stub(:find).with("37") { mock_test_question }
      get :edit, :id => "37"
      assigns(:test_question).should be(mock_test_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created test_question as @test_question" do
        TestQuestion.stub(:new).with({'these' => 'params'}) { mock_test_question(:save => true) }
        post :create, :test_question => {'these' => 'params'}
        assigns(:test_question).should be(mock_test_question)
      end

      it "redirects to the created test_question" do
        TestQuestion.stub(:new) { mock_test_question(:save => true) }
        post :create, :test_question => {}
        response.should redirect_to(test_question_url(mock_test_question))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_question as @test_question" do
        TestQuestion.stub(:new).with({'these' => 'params'}) { mock_test_question(:save => false) }
        post :create, :test_question => {'these' => 'params'}
        assigns(:test_question).should be(mock_test_question)
      end

      it "re-renders the 'new' template" do
        TestQuestion.stub(:new) { mock_test_question(:save => false) }
        post :create, :test_question => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_question" do
        TestQuestion.stub(:find).with("37") { mock_test_question }
        mock_test_question.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :test_question => {'these' => 'params'}
      end

      it "assigns the requested test_question as @test_question" do
        TestQuestion.stub(:find) { mock_test_question(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:test_question).should be(mock_test_question)
      end

      it "redirects to the test_question" do
        TestQuestion.stub(:find) { mock_test_question(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(test_question_url(mock_test_question))
      end
    end

    describe "with invalid params" do
      it "assigns the test_question as @test_question" do
        TestQuestion.stub(:find) { mock_test_question(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:test_question).should be(mock_test_question)
      end

      it "re-renders the 'edit' template" do
        TestQuestion.stub(:find) { mock_test_question(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_question" do
      TestQuestion.stub(:find).with("37") { mock_test_question }
      mock_test_question.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the test_questions list" do
      TestQuestion.stub(:find) { mock_test_question }
      delete :destroy, :id => "1"
      response.should redirect_to(test_questions_url)
    end
  end

end
